namespace LittleArkFoundation.Areas.Admin.Models.Statistics
{
    public class StatisticsModel
    {
        public int Id { get; set; }
        public string? Type { get; set; }
        public DateOnly? Date { get; set; }
        public int? UserID { get; set; }
        public int? i_GovernmentHospital { get; set; }
        public int? i_PrivateHospitalClinics { get; set; }
        public int? i_Politicians { get; set; }
        public int? i_Media { get; set; }
        public int? i_HealthCareTeam { get; set; }
        public int? i_NGOs { get; set; }
        public int? i_GovernmentAgencies { get; set; }
        public int? i_WalkIn { get; set; }
        public int? i_Others { get; set; }
        public int? ii_DuringCensus_NewCases { get; set; }
        public int? ii_DuringCensus_OldCases { get; set; }
        public int? ii_ClosedSummary { get; set; }
        public int? ii_NoPatients_PWD { get; set; }
        public int? ii_NoPatients_IndigenousPeople { get; set; }
        public int? ii_NoPatients_GovernmentWorkers { get; set; }
        public int? ii_Planning_SocioEconomicClassification { get; set; }
        public int? ii_Planning_PreAdmissionPlanning { get; set; }
        public int? ii_Planning_InformationServices { get; set; }
        public int? ii_Concrete_ProvisionDiscount { get; set; }
        public int? ii_Concrete_FacilitatingReferrals { get; set; }
        public int? ii_Concrete_OutgoingReferrals_MedicalAssistance { get; set; }
        public int? ii_Concrete_OutgoingReferrals_DiscountProcedure { get; set; }
        public int? ii_Concrete_OutgoingReferrals_TransportationFare { get; set; }
        public int? ii_Concrete_OutgoingReferrals_InstitutionalPlacement { get; set; }
        public int? ii_Concrete_OutgoingReferrals_TemporaryShelter { get; set; }
        public int? ii_Concrete_OutgoingReferrals_FuneralAssistance { get; set; }
        public int? ii_Concrete_OutgoingReferrals_OthersSpecify { get; set; }
        public int? ii_Concrete_IncomingReferrals { get; set; }
        public int? ii_Psychosocial_TenLeading_StressFamily { get; set; }
        public int? ii_Psychosocial_TenLeading_RefusalPatientTakeHome { get; set; }
        public int? ii_Psychosocial_TenLeading_AnxietyHealth { get; set; }
        public int? ii_Psychosocial_TenLeading_MaritalProblem { get; set; }
        public int? ii_Psychosocial_TenLeading_RefusalPatientTreatment { get; set; }
        public int? ii_Psychosocial_TenLeading_UnbecomingAttitude { get; set; }
        public int? ii_Psychosocial_TenLeading_EmotionalProblem { get; set; }
        public int? ii_Psychosocial_TenLeading_NeglectedChildren { get; set; }
        public int? ii_Psychosocial_TenLeading_SexuallyAbuse { get; set; }
        public int? ii_Psychosocial_TenLeading_AdjustedProblem { get; set; }
        public int? ii_Psychosocial_FamilyCounseling_SocialWorker { get; set; }
        public int? ii_Psychosocial_FamilyCounseling_HealthCareTeam { get; set; }
        public int? ii_Psychosocial_PsychosocialCrisis { get; set; }
        public int? ii_Psychosocial_GroupWork { get; set; }
        public int? ii_Psychosocial_PatientsEducation { get; set; }
        public int? ii_Psychosocial_MutualSupport { get; set; }
        public int? ii_Psychosocial_AdvocacyGroup { get; set; }
        public int? ii_Discharges_DischargePlanning { get; set; }
        public int? ii_Discharges_FacilitationDischarge { get; set; }
        public int? ii_Discharges_PreTerminationCounseling { get; set; }
        public int? ii_Discharges_HomeConduction { get; set; }
        public int? ii_Support_Ward_Individual { get; set; }
        public int? ii_Support_Ward_Team { get; set; }
        public int? ii_Case_MultiDisciplinary { get; set; }
        public int? ii_Case_MSWD { get; set; }
        public int? ii_FollowUp_HomeVisit { get; set; }
        public int? ii_FollowUp_LettersSent { get; set; }
        public int? ii_FollowUp_ContactRelativesTelephone { get; set; }
        public int? ii_FollowUp_ContactRelativesMassMedia { get; set; }
        public int? ii_Coordination_Physicians { get; set; }
        public int? ii_Coordination_Nurses { get; set; }
        public int? ii_Coordination_Pharmacist { get; set; }
        public int? ii_Coordination_Nutritionist { get; set; }
        public int? ii_Coordination_OtherStaff { get; set; }
        public int? ii_Coordination_Management { get; set; }
        public int? ii_Consultive_Physicians { get; set; }
        public int? ii_Consultive_OfficeStaff { get; set; }
        public int? ii_Consultive_OutsideHospital { get; set; }
        public int? iii_PreAdmissionCounseling { get; set; }
        public int? iii_IntakeInterview { get; set; }
        public int? iii_CollateralInterview { get; set; }
        public int? iii_IssuanceMSSCard { get; set; }
        public int? iii_IndicateClassification { get; set; }
        public int? iii_PsychosocialAssessment { get; set; }
        public int? iii_PsychosocialCounseling { get; set; }
        public int? iii_CoordinationMultidisciplinary { get; set; }
        public int? iii_CompletionIntakeForm { get; set; }
        public int? iii_HealthEducation { get; set; }
        public int? iii_CrisisIntervention { get; set; }
        public int? iii_ConcreteServices_Facilitation { get; set; }
        public int? iii_ConcreteServices_Transportation { get; set; }
        public int? iii_ConcreteServices_MaterialAssistance { get; set; }
        public int? iii_ConcreteServices_FinancialAssistance { get; set; }
        public int? iii_Referral_Facilitating { get; set; }
        public int? iii_Referral_Preparing { get; set; }
        public int? iii_Referral_Coordination { get; set; }
        public int? iii_WardRounds { get; set; }
        public int? iii_HomeVisitation { get; set; }
        public int? iii_AdvocacyRole { get; set; }
        public int? iii_Education { get; set; }
        public int? iii_Therapeutic_Abandoned { get; set; }
        public int? iii_Therapeutic_SexuallyAbused { get; set; }
        public int? iii_Therapeutic_Neglected { get; set; }
        public int? iii_Therapeutic_Battered { get; set; }
        public int? iii_ProtectiveServices { get; set; }
        public int? iii_GriefWork { get; set; }
        public int? iii_Behavioral { get; set; }
        public int? iii_Networking { get; set; }
        public int? iii_Politicians { get; set; }
        public int? iii_CoordinationMassMedia { get; set; }
        public int? iii_ConsultationAdvisory { get; set; }
        public int? iii_AttendanceCaseConference { get; set; }
        public int? iii_AttendanceClinical_Discharge { get; set; }
        public int? iii_AttendanceClinical_Facilitation { get; set; }
        public int? iii_AttendanceClinical_Home { get; set; }
        public int? iii_FollowUpServices { get; set; }
        public int? iii_Documentation_Profile { get; set; }
        public int? iii_Documentation_ProgressNotes { get; set; }
        public int? iii_Documentation_GroupWork { get; set; }
        public int? iii_Documentation_SocialCase { get; set; }
        public int? iii_Documentation_HomeVisit { get; set; }
        public int? iii_Palliative { get; set; }
        public int? iii_FacilitationUnclaimed { get; set; }
        public int? iii_PostDischarge { get; set; }
        public int? iii_FollowUpServicesText { get; set; }
        public int? iii_FollowUpTreatment { get; set; }
        public int? iii_FollowUpRehabilitation { get; set; }
        public int? iii_Rehabilitation_Skills { get; set; }
        public int? iii_Rehabilitation_Job { get; set; }
        public int? iii_Rehabilitation_Capital { get; set; }
        public int? iii_MSWDFund { get; set; }
        public int? iii_HospitalActivity { get; set; }
        public int? iii_LinkageDonors { get; set; }
    }
}
